services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=data1
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    user: root