require_relative '../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/@capacitor/ios'
  
  # 添加Capacitor插件
  pod 'CapacitorApp', :path => '../../../node_modules/@capacitor/app'
  pod 'CapacitorHaptics', :path => '../../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../../node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :path => '../../../node_modules/@capacitor/status-bar'
  pod 'CapacitorDevice', :path => '../../../node_modules/@capacitor/device'
  pod 'CapacitorNetwork', :path => '../../../node_modules/@capacitor/network'
  pod 'CapacitorStorage', :path => '../../../node_modules/@capacitor/preferences'
  pod 'CapacitorFilesystem', :path => '../../../node_modules/@capacitor/filesystem'
  pod 'CapacitorCamera', :path => '../../../node_modules/@capacitor/camera'
  pod 'CapacitorGeolocation', :path => '../../../node_modules/@capacitor/geolocation'
  pod 'CapacitorLocalNotifications', :path => '../../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorPushNotifications', :path => '../../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorSplashScreen', :path => '../../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorActionSheet', :path => '../../../node_modules/@capacitor/action-sheet'
  pod 'CapacitorToast', :path => '../../../node_modules/@capacitor/toast'
  pod 'CapacitorDialog', :path => '../../../node_modules/@capacitor/dialog'
  pod 'CapacitorShare', :path => '../../../node_modules/@capacitor/share'
  pod 'CapacitorClipboard', :path => '../../../node_modules/@capacitor/clipboard'
  pod 'CapacitorScreenReader', :path => '../../../node_modules/@capacitor/screen-reader'
  pod 'CapacitorTextZoom', :path => '../../../node_modules/@capacitor/text-zoom'
  pod 'CapacitorAccessibility', :path => '../../../node_modules/@capacitor/accessibility'
  pod 'CapacitorBrowser', :path => '../../../node_modules/@capacitor/browser'
  pod 'CapacitorHttp', :path => '../../../node_modules/@capacitor/http'
  pod 'CapacitorKeepAwake', :path => '../../../node_modules/@capacitor/keep-awake'
  pod 'CapacitorMotion', :path => '../../../node_modules/@capacitor/motion'
  pod 'CapacitorScreenOrientation', :path => '../../../node_modules/@capacitor/screen-orientation'
  pod 'CapacitorVibration', :path => '../../../node_modules/@capacitor/vibration'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  
  # 添加第三方库
  pod 'Alamofire', '~> 5.0'  # 网络请求
  pod 'SDWebImage', '~> 5.0'  # 图片加载
  pod 'SnapKit', '~> 5.0'     # 自动布局
  pod 'SwiftyJSON', '~> 5.0'  # JSON解析
  pod 'RealmSwift', '~> 10.0' # 本地数据库
  pod 'CryptoSwift', '~> 1.0' # 加密
  pod 'IQKeyboardManagerSwift', '~> 6.0' # 键盘管理
  pod 'Toast-Swift', '~> 5.0'  # 提示框
  pod 'MBProgressHUD', '~> 1.0' # 加载指示器
  pod 'FSCalendar', '~> 2.0'   # 日历组件
  pod 'Charts', '~> 4.0'       # 图表组件
  pod 'Lottie', '~> 4.0'       # 动画
  pod 'Firebase/Analytics'     # Firebase分析
  pod 'Firebase/Crashlytics'   # Firebase崩溃报告
  pod 'Firebase/Messaging'     # Firebase推送
end

post_install do |installer|
  assertDeploymentTarget(installer)
  
  # 配置构建设置
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      
      # 添加必要的链接器标志
      config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
      config.build_settings['OTHER_LDFLAGS'] << '-ObjC'
    end
  end
end
